// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Core.proto
// Protobuf C++ Version: 5.28.0-dev

#include "Core.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NFProto {

inline constexpr NetMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msgcontent_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgmainid_{static_cast< ::NFProto::MsgMainIdEnum >(0)},
        msgsubid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NetMsg::NetMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NetMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetMsgDefaultTypeInternal() {}
  union {
    NetMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetMsgDefaultTypeInternal _NetMsg_default_instance_;
}  // namespace NFProto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Core_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Core_2eproto = nullptr;
const ::uint32_t
    TableStruct_Core_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NFProto::NetMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NFProto::NetMsg, _impl_.msgmainid_),
        PROTOBUF_FIELD_OFFSET(::NFProto::NetMsg, _impl_.msgsubid_),
        PROTOBUF_FIELD_OFFSET(::NFProto::NetMsg, _impl_.msgcontent_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NFProto::NetMsg)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NFProto::_NetMsg_default_instance_._instance,
};
const char descriptor_table_protodef_Core_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nCore.proto\022\007NFProto\032\014Define.proto\"Y\n\006N"
    "etMsg\022)\n\tMsgMainId\030\001 \001(\0162\026.NFProto.MsgMa"
    "inIdEnum\022\020\n\010MsgSubId\030\002 \001(\005\022\022\n\nMsgContent"
    "\030\003 \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Core_2eproto_deps[1] =
    {
        &::descriptor_table_Define_2eproto,
};
static ::absl::once_flag descriptor_table_Core_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Core_2eproto = {
    false,
    false,
    134,
    descriptor_table_protodef_Core_2eproto,
    "Core.proto",
    &descriptor_table_Core_2eproto_once,
    descriptor_table_Core_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_Core_2eproto::offsets,
    file_level_enum_descriptors_Core_2eproto,
    file_level_service_descriptors_Core_2eproto,
};
namespace NFProto {
// ===================================================================

class NetMsg::_Internal {
 public:
};

NetMsg::NetMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NFProto.NetMsg)
}
inline PROTOBUF_NDEBUG_INLINE NetMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NFProto::NetMsg& from_msg)
      : msgcontent_(arena, from.msgcontent_),
        _cached_size_{0} {}

NetMsg::NetMsg(
    ::google::protobuf::Arena* arena,
    const NetMsg& from)
    : ::google::protobuf::Message(arena) {
  NetMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgmainid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, msgmainid_),
           offsetof(Impl_, msgsubid_) -
               offsetof(Impl_, msgmainid_) +
               sizeof(Impl_::msgsubid_));

  // @@protoc_insertion_point(copy_constructor:NFProto.NetMsg)
}
inline PROTOBUF_NDEBUG_INLINE NetMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msgcontent_(arena),
        _cached_size_{0} {}

inline void NetMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgmainid_),
           0,
           offsetof(Impl_, msgsubid_) -
               offsetof(Impl_, msgmainid_) +
               sizeof(Impl_::msgsubid_));
}
NetMsg::~NetMsg() {
  // @@protoc_insertion_point(destructor:NFProto.NetMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NetMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msgcontent_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NetMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NetMsg, _impl_._cached_size_),
              false,
          },
          &NetMsg::MergeImpl,
          &NetMsg::kDescriptorMethods,
          &descriptor_table_Core_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> NetMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NetMsg_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NFProto::NetMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .NFProto.MsgMainIdEnum MsgMainId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetMsg, _impl_.msgmainid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgmainid_)}},
    // int32 MsgSubId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetMsg, _impl_.msgsubid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgsubid_)}},
    // bytes MsgContent = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgcontent_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .NFProto.MsgMainIdEnum MsgMainId = 1;
    {PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgmainid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 MsgSubId = 2;
    {PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgsubid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes MsgContent = 3;
    {PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgcontent_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NetMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:NFProto.NetMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msgcontent_.ClearToEmpty();
  ::memset(&_impl_.msgmainid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.msgsubid_) -
      reinterpret_cast<char*>(&_impl_.msgmainid_)) + sizeof(_impl_.msgsubid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NetMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NFProto.NetMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .NFProto.MsgMainIdEnum MsgMainId = 1;
  if (this->_internal_msgmainid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_msgmainid(), target);
  }

  // int32 MsgSubId = 2;
  if (this->_internal_msgsubid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_msgsubid(), target);
  }

  // bytes MsgContent = 3;
  if (!this->_internal_msgcontent().empty()) {
    const std::string& _s = this->_internal_msgcontent();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFProto.NetMsg)
  return target;
}

::size_t NetMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFProto.NetMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // bytes MsgContent = 3;
  if (!this->_internal_msgcontent().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_msgcontent());
  }

  // .NFProto.MsgMainIdEnum MsgMainId = 1;
  if (this->_internal_msgmainid() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_msgmainid());
  }

  // int32 MsgSubId = 2;
  if (this->_internal_msgsubid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_msgsubid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NetMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NetMsg*>(&to_msg);
  auto& from = static_cast<const NetMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NFProto.NetMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msgcontent().empty()) {
    _this->_internal_set_msgcontent(from._internal_msgcontent());
  }
  if (from._internal_msgmainid() != 0) {
    _this->_impl_.msgmainid_ = from._impl_.msgmainid_;
  }
  if (from._internal_msgsubid() != 0) {
    _this->_impl_.msgsubid_ = from._impl_.msgsubid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NetMsg::CopyFrom(const NetMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFProto.NetMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetMsg::InternalSwap(NetMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msgcontent_, &other->_impl_.msgcontent_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgsubid_)
      + sizeof(NetMsg::_impl_.msgsubid_)
      - PROTOBUF_FIELD_OFFSET(NetMsg, _impl_.msgmainid_)>(
          reinterpret_cast<char*>(&_impl_.msgmainid_),
          reinterpret_cast<char*>(&other->_impl_.msgmainid_));
}

::google::protobuf::Metadata NetMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NFProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Core_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
