// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DailyAsk.proto
// Protobuf C++ Version: 5.28.0-dev

#include "DailyAsk.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MsgDailyAsk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MsgDailyAsk::MsgDailyAsk(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MsgDailyAskDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgDailyAskDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgDailyAskDefaultTypeInternal() {}
  union {
    MsgDailyAsk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgDailyAskDefaultTypeInternal _MsgDailyAsk_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_DailyAsk_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_DailyAsk_2eproto = nullptr;
const ::uint32_t
    TableStruct_DailyAsk_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MsgDailyAsk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MsgDailyAsk, _impl_.content_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MsgDailyAsk)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_MsgDailyAsk_default_instance_._instance,
};
const char descriptor_table_protodef_DailyAsk_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016DailyAsk.proto\"\036\n\013MsgDailyAsk\022\017\n\007Conte"
    "nt\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_DailyAsk_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_DailyAsk_2eproto = {
    false,
    false,
    56,
    descriptor_table_protodef_DailyAsk_2eproto,
    "DailyAsk.proto",
    &descriptor_table_DailyAsk_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_DailyAsk_2eproto::offsets,
    file_level_enum_descriptors_DailyAsk_2eproto,
    file_level_service_descriptors_DailyAsk_2eproto,
};
// ===================================================================

class MsgDailyAsk::_Internal {
 public:
};

MsgDailyAsk::MsgDailyAsk(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MsgDailyAsk)
}
inline PROTOBUF_NDEBUG_INLINE MsgDailyAsk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MsgDailyAsk& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

MsgDailyAsk::MsgDailyAsk(
    ::google::protobuf::Arena* arena,
    const MsgDailyAsk& from)
    : ::google::protobuf::Message(arena) {
  MsgDailyAsk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MsgDailyAsk)
}
inline PROTOBUF_NDEBUG_INLINE MsgDailyAsk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void MsgDailyAsk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MsgDailyAsk::~MsgDailyAsk() {
  // @@protoc_insertion_point(destructor:MsgDailyAsk)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MsgDailyAsk::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.content_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MsgDailyAsk::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MsgDailyAsk, _impl_._cached_size_),
              false,
          },
          &MsgDailyAsk::MergeImpl,
          &MsgDailyAsk::kDescriptorMethods,
          &descriptor_table_DailyAsk_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 27, 2> MsgDailyAsk::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MsgDailyAsk_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MsgDailyAsk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MsgDailyAsk, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Content = 1;
    {PROTOBUF_FIELD_OFFSET(MsgDailyAsk, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\7\0\0\0\0\0\0"
    "MsgDailyAsk"
    "Content"
  }},
};

PROTOBUF_NOINLINE void MsgDailyAsk::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgDailyAsk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MsgDailyAsk::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgDailyAsk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Content = 1;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MsgDailyAsk.Content");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgDailyAsk)
  return target;
}

::size_t MsgDailyAsk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MsgDailyAsk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Content = 1;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MsgDailyAsk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MsgDailyAsk*>(&to_msg);
  auto& from = static_cast<const MsgDailyAsk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MsgDailyAsk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MsgDailyAsk::CopyFrom(const MsgDailyAsk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgDailyAsk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MsgDailyAsk::InternalSwap(MsgDailyAsk* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata MsgDailyAsk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_DailyAsk_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
