// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Define.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_Define_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Define_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Define_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Define_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Define_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum MsgMainIdEnum : int {
  Invalid = 0,
  HeatBeat = 1,
  DailyAsk = 2,
  MsgMainIdEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MsgMainIdEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MsgMainIdEnum_IsValid(int value);
extern const uint32_t MsgMainIdEnum_internal_data_[];
constexpr MsgMainIdEnum MsgMainIdEnum_MIN = static_cast<MsgMainIdEnum>(0);
constexpr MsgMainIdEnum MsgMainIdEnum_MAX = static_cast<MsgMainIdEnum>(2);
constexpr int MsgMainIdEnum_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
MsgMainIdEnum_descriptor();
template <typename T>
const std::string& MsgMainIdEnum_Name(T value) {
  static_assert(std::is_same<T, MsgMainIdEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MsgMainIdEnum_Name().");
  return MsgMainIdEnum_Name(static_cast<MsgMainIdEnum>(value));
}
template <>
inline const std::string& MsgMainIdEnum_Name(MsgMainIdEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MsgMainIdEnum_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool MsgMainIdEnum_Parse(absl::string_view name, MsgMainIdEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgMainIdEnum>(
      MsgMainIdEnum_descriptor(), name, value);
}
enum MsgSubIdEnum : int {
  NoSpecific = 0,
  MsgSubIdEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MsgSubIdEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MsgSubIdEnum_IsValid(int value);
extern const uint32_t MsgSubIdEnum_internal_data_[];
constexpr MsgSubIdEnum MsgSubIdEnum_MIN = static_cast<MsgSubIdEnum>(0);
constexpr MsgSubIdEnum MsgSubIdEnum_MAX = static_cast<MsgSubIdEnum>(0);
constexpr int MsgSubIdEnum_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor*
MsgSubIdEnum_descriptor();
template <typename T>
const std::string& MsgSubIdEnum_Name(T value) {
  static_assert(std::is_same<T, MsgSubIdEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MsgSubIdEnum_Name().");
  return MsgSubIdEnum_Name(static_cast<MsgSubIdEnum>(value));
}
template <>
inline const std::string& MsgSubIdEnum_Name(MsgSubIdEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MsgSubIdEnum_descriptor,
                                                 0, 0>(
      static_cast<int>(value));
}
inline bool MsgSubIdEnum_Parse(absl::string_view name, MsgSubIdEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgSubIdEnum>(
      MsgSubIdEnum_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::MsgMainIdEnum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MsgMainIdEnum>() {
  return ::MsgMainIdEnum_descriptor();
}
template <>
struct is_proto_enum<::MsgSubIdEnum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MsgSubIdEnum>() {
  return ::MsgSubIdEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Define_2eproto_2epb_2eh
