// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoFiles/Define.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ProtoFiles_2fDefine_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtoFiles_2fDefine_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ProtoFiles_2fDefine_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum MainMsgId : int {
  Invalid = 0,
  HeatBeat = 1,
  MainMsgId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MainMsgId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MainMsgId_IsValid(int value);
extern const uint32_t MainMsgId_internal_data_[];
constexpr MainMsgId MainMsgId_MIN = static_cast<MainMsgId>(0);
constexpr MainMsgId MainMsgId_MAX = static_cast<MainMsgId>(1);
constexpr int MainMsgId_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
MainMsgId_descriptor();
template <typename T>
const std::string& MainMsgId_Name(T value) {
  static_assert(std::is_same<T, MainMsgId>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MainMsgId_Name().");
  return MainMsgId_Name(static_cast<MainMsgId>(value));
}
template <>
inline const std::string& MainMsgId_Name(MainMsgId value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MainMsgId_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool MainMsgId_Parse(absl::string_view name, MainMsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MainMsgId>(
      MainMsgId_descriptor(), name, value);
}
enum SubMsgId : int {
  NotValid = 0,
  SubMsgId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SubMsgId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SubMsgId_IsValid(int value);
extern const uint32_t SubMsgId_internal_data_[];
constexpr SubMsgId SubMsgId_MIN = static_cast<SubMsgId>(0);
constexpr SubMsgId SubMsgId_MAX = static_cast<SubMsgId>(0);
constexpr int SubMsgId_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor*
SubMsgId_descriptor();
template <typename T>
const std::string& SubMsgId_Name(T value) {
  static_assert(std::is_same<T, SubMsgId>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SubMsgId_Name().");
  return SubMsgId_Name(static_cast<SubMsgId>(value));
}
template <>
inline const std::string& SubMsgId_Name(SubMsgId value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SubMsgId_descriptor,
                                                 0, 0>(
      static_cast<int>(value));
}
inline bool SubMsgId_Parse(absl::string_view name, SubMsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SubMsgId>(
      SubMsgId_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::MainMsgId> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MainMsgId>() {
  return ::MainMsgId_descriptor();
}
template <>
struct is_proto_enum<::SubMsgId> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::SubMsgId>() {
  return ::SubMsgId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh
