// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Define.proto
// Protobuf C++ Version: 5.28.0-dev

#include "Define.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NFProto {
}  // namespace NFProto
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Define_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Define_2eproto = nullptr;
const ::uint32_t TableStruct_Define_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Define_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Define.proto\022\007NFProto\032\014Extend.proto*f\n"
    "\rMsgMainIdEnum\022\013\n\007Invalid\020\000\022\014\n\010HeatBeat\020"
    "\001\022:\n\010DailyAsk\020\002\032,\212K\023NFProto.C2SDailyAsk\222"
    "K\023NFProto.S2CDailyAsk*\036\n\014MsgSubIdEnum\022\016\n"
    "\nNoSpecific\020\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Define_2eproto_deps[1] =
    {
        &::descriptor_table_Extend_2eproto,
};
static ::absl::once_flag descriptor_table_Define_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Define_2eproto = {
    false,
    false,
    181,
    descriptor_table_protodef_Define_2eproto,
    "Define.proto",
    &descriptor_table_Define_2eproto_once,
    descriptor_table_Define_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_Define_2eproto::offsets,
    file_level_enum_descriptors_Define_2eproto,
    file_level_service_descriptors_Define_2eproto,
};
namespace NFProto {
const ::google::protobuf::EnumDescriptor* MsgMainIdEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Define_2eproto);
  return file_level_enum_descriptors_Define_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgMainIdEnum_internal_data_[] = {
    196608u, 0u, };
bool MsgMainIdEnum_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* MsgSubIdEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Define_2eproto);
  return file_level_enum_descriptors_Define_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t MsgSubIdEnum_internal_data_[] = {
    65536u, 0u, };
bool MsgSubIdEnum_IsValid(int value) {
  return 0 <= value && value <= 0;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NFProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Define_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
