// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Core.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_Core_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Core_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Define.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Core_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Core_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Core_2eproto;
class NetMsg;
struct NetMsgDefaultTypeInternal;
extern NetMsgDefaultTypeInternal _NetMsg_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class NetMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetMsg) */ {
 public:
  inline NetMsg() : NetMsg(nullptr) {}
  ~NetMsg() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMsg(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMsg(const NetMsg& from) : NetMsg(nullptr, from) {}
  inline NetMsg(NetMsg&& from) noexcept
      : NetMsg(nullptr, std::move(from)) {}
  inline NetMsg& operator=(const NetMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMsg& operator=(NetMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMsg* internal_default_instance() {
    return reinterpret_cast<const NetMsg*>(
        &_NetMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NetMsg& a, NetMsg& b) { a.Swap(&b); }
  inline void Swap(NetMsg* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMsg* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMsg* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<NetMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetMsg& from) { NetMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NetMsg* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMsg"; }

 protected:
  explicit NetMsg(::google::protobuf::Arena* arena);
  NetMsg(::google::protobuf::Arena* arena, const NetMsg& from);
  NetMsg(::google::protobuf::Arena* arena, NetMsg&& from) noexcept
      : NetMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgContentFieldNumber = 3,
    kMsgMainIdFieldNumber = 1,
    kMsgSubIdFieldNumber = 2,
  };
  // bytes MsgContent = 3;
  void clear_msgcontent() ;
  const std::string& msgcontent() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msgcontent(Arg_&& arg, Args_... args);
  std::string* mutable_msgcontent();
  PROTOBUF_NODISCARD std::string* release_msgcontent();
  void set_allocated_msgcontent(std::string* value);

  private:
  const std::string& _internal_msgcontent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msgcontent(
      const std::string& value);
  std::string* _internal_mutable_msgcontent();

  public:
  // .MsgMainIdEnum MsgMainId = 1;
  void clear_msgmainid() ;
  ::MsgMainIdEnum msgmainid() const;
  void set_msgmainid(::MsgMainIdEnum value);

  private:
  ::MsgMainIdEnum _internal_msgmainid() const;
  void _internal_set_msgmainid(::MsgMainIdEnum value);

  public:
  // int32 MsgSubId = 2;
  void clear_msgsubid() ;
  ::int32_t msgsubid() const;
  void set_msgsubid(::int32_t value);

  private:
  ::int32_t _internal_msgsubid() const;
  void _internal_set_msgsubid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NetMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMsg_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMsg& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msgcontent_;
    int msgmainid_;
    ::int32_t msgsubid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Core_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NetMsg

// .MsgMainIdEnum MsgMainId = 1;
inline void NetMsg::clear_msgmainid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgmainid_ = 0;
}
inline ::MsgMainIdEnum NetMsg::msgmainid() const {
  // @@protoc_insertion_point(field_get:NetMsg.MsgMainId)
  return _internal_msgmainid();
}
inline void NetMsg::set_msgmainid(::MsgMainIdEnum value) {
  _internal_set_msgmainid(value);
  // @@protoc_insertion_point(field_set:NetMsg.MsgMainId)
}
inline ::MsgMainIdEnum NetMsg::_internal_msgmainid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::MsgMainIdEnum>(_impl_.msgmainid_);
}
inline void NetMsg::_internal_set_msgmainid(::MsgMainIdEnum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgmainid_ = value;
}

// int32 MsgSubId = 2;
inline void NetMsg::clear_msgsubid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgsubid_ = 0;
}
inline ::int32_t NetMsg::msgsubid() const {
  // @@protoc_insertion_point(field_get:NetMsg.MsgSubId)
  return _internal_msgsubid();
}
inline void NetMsg::set_msgsubid(::int32_t value) {
  _internal_set_msgsubid(value);
  // @@protoc_insertion_point(field_set:NetMsg.MsgSubId)
}
inline ::int32_t NetMsg::_internal_msgsubid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgsubid_;
}
inline void NetMsg::_internal_set_msgsubid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgsubid_ = value;
}

// bytes MsgContent = 3;
inline void NetMsg::clear_msgcontent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgcontent_.ClearToEmpty();
}
inline const std::string& NetMsg::msgcontent() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetMsg.MsgContent)
  return _internal_msgcontent();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NetMsg::set_msgcontent(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgcontent_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetMsg.MsgContent)
}
inline std::string* NetMsg::mutable_msgcontent() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msgcontent();
  // @@protoc_insertion_point(field_mutable:NetMsg.MsgContent)
  return _s;
}
inline const std::string& NetMsg::_internal_msgcontent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgcontent_.Get();
}
inline void NetMsg::_internal_set_msgcontent(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgcontent_.Set(value, GetArena());
}
inline std::string* NetMsg::_internal_mutable_msgcontent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msgcontent_.Mutable( GetArena());
}
inline std::string* NetMsg::release_msgcontent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetMsg.MsgContent)
  return _impl_.msgcontent_.Release();
}
inline void NetMsg::set_allocated_msgcontent(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgcontent_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.msgcontent_.IsDefault()) {
          _impl_.msgcontent_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NetMsg.MsgContent)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Core_2eproto_2epb_2eh
