// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Extend.proto
// Protobuf C++ Version: 5.28.0-dev

#include "Extend.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NFProto {
}  // namespace NFProto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Extend_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Extend_2eproto = nullptr;
const ::uint32_t TableStruct_Extend_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Extend_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Extend.proto\022\007NFProto\032 google/protobuf"
    "/descriptor.proto:9\n\rSpecificProto\022!.goo"
    "gle.protobuf.EnumValueOptions\030\261\t \001(\010:7\n\013"
    "NetReqProto\022!.google.protobuf.EnumValueO"
    "ptions\030\262\t \001(\t:7\n\013NetRspProto\022!.google.pr"
    "otobuf.EnumValueOptions\030\263\t \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Extend_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_Extend_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Extend_2eproto = {
    false,
    false,
    238,
    descriptor_table_protodef_Extend_2eproto,
    "Extend.proto",
    &descriptor_table_Extend_2eproto_once,
    descriptor_table_Extend_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_Extend_2eproto::offsets,
    file_level_enum_descriptors_Extend_2eproto,
    file_level_service_descriptors_Extend_2eproto,
};
namespace NFProto {
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::EnumValueOptions, ::_pbi::PrimitiveTypeTraits< bool >,
                            8, false>
            SpecificProto(kSpecificProtoFieldNumber, false);
const std::string NetReqProto_default("");
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::EnumValueOptions, ::_pbi::StringTypeTraits,
                            9, false>
            NetReqProto(kNetReqProtoFieldNumber, NetReqProto_default);
const std::string NetRspProto_default("");
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::EnumValueOptions, ::_pbi::StringTypeTraits,
                            9, false>
            NetRspProto(kNetRspProtoFieldNumber, NetRspProto_default);
// @@protoc_insertion_point(namespace_scope)
}  // namespace NFProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Extend_2eproto),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1201, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1202, 9,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1203, 9,
            false, false),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
