// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoFiles/Define.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ProtoFiles_2fDefine_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtoFiles_2fDefine_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ProtoFiles_2fDefine_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum MainMsg : int {
  Invalid = 0,
  HeadBeat = 1,
  MainMsg_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MainMsg_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MainMsg_IsValid(int value);
extern const uint32_t MainMsg_internal_data_[];
constexpr MainMsg MainMsg_MIN = static_cast<MainMsg>(0);
constexpr MainMsg MainMsg_MAX = static_cast<MainMsg>(1);
constexpr int MainMsg_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
MainMsg_descriptor();
template <typename T>
const std::string& MainMsg_Name(T value) {
  static_assert(std::is_same<T, MainMsg>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MainMsg_Name().");
  return MainMsg_Name(static_cast<MainMsg>(value));
}
template <>
inline const std::string& MainMsg_Name(MainMsg value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MainMsg_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool MainMsg_Parse(absl::string_view name, MainMsg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MainMsg>(
      MainMsg_descriptor(), name, value);
}
enum SubMsgID : int {
  Notvalid = 0,
  SubMsgID_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SubMsgID_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SubMsgID_IsValid(int value);
extern const uint32_t SubMsgID_internal_data_[];
constexpr SubMsgID SubMsgID_MIN = static_cast<SubMsgID>(0);
constexpr SubMsgID SubMsgID_MAX = static_cast<SubMsgID>(0);
constexpr int SubMsgID_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor*
SubMsgID_descriptor();
template <typename T>
const std::string& SubMsgID_Name(T value) {
  static_assert(std::is_same<T, SubMsgID>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SubMsgID_Name().");
  return SubMsgID_Name(static_cast<SubMsgID>(value));
}
template <>
inline const std::string& SubMsgID_Name(SubMsgID value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SubMsgID_descriptor,
                                                 0, 0>(
      static_cast<int>(value));
}
inline bool SubMsgID_Parse(absl::string_view name, SubMsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SubMsgID>(
      SubMsgID_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::MainMsg> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MainMsg>() {
  return ::MainMsg_descriptor();
}
template <>
struct is_proto_enum<::SubMsgID> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::SubMsgID>() {
  return ::SubMsgID_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ProtoFiles_2fDefine_2eproto_2epb_2eh
