// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoFiles/Define.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoFiles/Define.proto</summary>
public static partial class DefineReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoFiles/Define.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DefineReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdQcm90b0ZpbGVzL0RlZmluZS5wcm90byomCglNYWluTXNnSWQSCwoHSW52",
          "YWxpZBAAEgwKCEhlYXRCZWF0EAEqGAoIU3ViTXNnSWQSDAoITm90VmFsaWQQ",
          "AGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MainMsgId), typeof(global::SubMsgId), }, null, null));
  }
  #endregion

}
#region Enums
public enum MainMsgId {
  [pbr::OriginalName("Invalid")] Invalid = 0,
  [pbr::OriginalName("HeatBeat")] HeatBeat = 1,
}

public enum SubMsgId {
  [pbr::OriginalName("NotValid")] NotValid = 0,
}

#endregion


#endregion Designer generated code
